/*
 * Cliente.java
 *
 * Generated with Matisse Schema Definition Language 9.1.12
 * Generation date: Wed Mar 03 13:26:56 2021
 */

// Note: the package and extends declarations are generated by mt_sdl, do not modify them

package banco;

import com.matisse.reflect.*;

/**
 * <code>Cliente</code> is a schema class generated by <code>mt_sdl</code>.
 * Any user-written classes will be found at the end of the file, after
 * the '// END of Matisse SDL Generated Code' comment.
 * Attribute types, default values, and relationship minimum and maximum
 * cardinality are stored in the database itself, not in this source code.
 * For more information, see <i>Getting Started with MATISSE</i>.
 */
public class Cliente extends com.matisse.reflect.MtObject {

    // BEGIN Matisse SDL Generated Code
    // DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
    /*
     * Generated with Matisse Schema Definition Language 9.1.12
     * Generation Date: Wed Mar 03 13:26:56 2021
     */

    /*
     * Class variables and methods
     */

    /** Class <code>Cliente</code> cache ID */
    private static int CID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtClass.Loader("banco.Cliente"));

    /**
     * Gets the <code>Cliente</code> class descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a class descriptor
     */
    public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtClass)db.getCachedObject(CID);
    }

    /**
     * Factory constructor. This constructor is called by <code>MtObjectFactory</code>.
     * It is public for technical reasons but is not intended to be called
     * directly by user methods.
     * @param db a database
     * @param mtOid an existing object ID in the database
     */
    public Cliente(com.matisse.MtDatabase db, int mtOid)  {
        super(db, mtOid);
    }

    /**
     * Cascaded constructor, used by subclasses to create a new object in the database.
     * It is protected for technical reasons but is not intended to be called
     * directly by user methods.
     * @param mtCls a class descriptor (the class to instantiate)
     */
    protected Cliente(com.matisse.reflect.MtClass mtCls)  {
        super(mtCls);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>instanceIterator(Cliente.class);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>instanceIterator(numObjPerBuffer, Cliente.class);
    }

    /**
     * Counts the number of instances of this class (and its subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getInstanceNumber();
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>ownInstanceIterator(Cliente.class);
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, Cliente.class);
    }

    /**
     * Counts the number of own instances of this class (excluding subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getOwnInstanceNumber();
    }

    /*
     * Attribute access methods
     */

    /* Attribute 'nombre' */

    /** Attribute <code>nombre</code> cache ID */
    private static int nombreCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("nombre",CID));

    /**
     * Gets the <code>nombre</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getNombreAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(nombreCID);
    }


    /**
     * Gets the <code>nombre</code> attribute value.
     * @return the value
     *
     * @see #setNombre
     * @see #removeNombre
     */
    public final String getNombre() {
        return getString(getNombreAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>nombre</code> attribute value.
     * @param val the new value
     *
     * @see #getNombre
     * @see #removeNombre
     */
    public final void setNombre(String val) {
        setString(getNombreAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>nombre</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getNombre
     * @see #setNombre
     */
    public final void removeNombre() {
        removeValue(getNombreAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getNombre
     * @see #setNombre
     */
    public final boolean isNombreDefaultValue() {
        return isDefaultValue(getNombreAttribute(getMtDatabase()));
    }


    /* Attribute 'dni' */

    /** Attribute <code>dni</code> cache ID */
    private static int dniCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("dni",CID));

    /**
     * Gets the <code>dni</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getDniAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(dniCID);
    }


    /**
     * Gets the <code>dni</code> attribute value.
     * @return the value
     *
     * @see #setDni
     * @see #removeDni
     */
    public final String getDni() {
        return getString(getDniAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>dni</code> attribute value.
     * @param val the new value
     *
     * @see #getDni
     * @see #removeDni
     */
    public final void setDni(String val) {
        setString(getDniAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>dni</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getDni
     * @see #setDni
     */
    public final void removeDni() {
        removeValue(getDniAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getDni
     * @see #setDni
     */
    public final boolean isDniDefaultValue() {
        return isDefaultValue(getDniAttribute(getMtDatabase()));
    }


    /*
     * Relationship access methods
     */

    /* Relationship 'tiene_cuentas' */

    /** Relationship <code>tiene_cuentas</code> cache ID */
    private static int tiene_cuentasCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtRelationship.Loader("tiene_cuentas",CID));

    /**
     * Gets the <code>tiene_cuentas</code> relationship descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a relationship descriptor object
     */
    public static com.matisse.reflect.MtRelationship getTiene_cuentasRelationship(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtRelationship)db.getCachedObject(tiene_cuentasCID);
    }

    /**
     * Gets the <code>tiene_cuentas</code> relationship's successors.
     * @return an array of objects
     *
     * @see #getTiene_cuentasSize
     * @see #tiene_cuentasIterator
     * @see #setTiene_cuentas
     * @see #removeTiene_cuentas
     */
    public final banco.Cuenta[] getTiene_cuentas() {
        return (banco.Cuenta[])getSuccessors(getTiene_cuentasRelationship(getMtDatabase()), banco.Cuenta.class);
    }

    /**
     * Counts the <code>tiene_cuentas</code> relationship's successors.
     * @return the number of successors
     *
     * @see #getTiene_cuentas
     * @see #tiene_cuentasIterator
     * @see #setTiene_cuentas
     * @see #removeTiene_cuentas
     */
    public final int getTiene_cuentasSize() {
        return getSuccessorSize(getTiene_cuentasRelationship(getMtDatabase()));
    }

    /**
     * Opens an iterator on the <code>tiene_cuentas</code> relationship's successors.
     * @param <E> a MtObject class     * @return an object iterator
     *
     * @see #getTiene_cuentas
     * @see #getTiene_cuentasSize
     * @see #setTiene_cuentas
     * @see #removeTiene_cuentas
     */
    public final <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> tiene_cuentasIterator() {
        return this.<E>successorIterator(getTiene_cuentasRelationship(getMtDatabase()), banco.Cuenta.class);
    }

    /**
     * Sets the <code>tiene_cuentas</code> relationship's successors.
     * @param succs an array of objects
     *
     * @see #getTiene_cuentas
     * @see #getTiene_cuentasSize
     * @see #tiene_cuentasIterator
     * @see #removeTiene_cuentas
     */
    public final void setTiene_cuentas(banco.Cuenta[] succs) {
        setSuccessors(getTiene_cuentasRelationship(getMtDatabase()), succs);
    }

    /**
     * Inserts one object at the beginning of the existing <code>tiene_cuentas</code> successors list.
     * @param succ the object to add
     *
     * @see #getTiene_cuentas
     * @see #getTiene_cuentasSize
     * @see #tiene_cuentasIterator
     * @see #setTiene_cuentas
     * @see #removeTiene_cuentas
     */
    public final void prependTiene_cuentas(banco.Cuenta succ) {
        prependSuccessor(getTiene_cuentasRelationship(getMtDatabase()), succ);
    }

    /**
     * Adds one object to the end of the existing <code>tiene_cuentas</code> successors list.
     * @param succ the object to add
     *
     * @see #getTiene_cuentas
     * @see #setTiene_cuentas
     * @see #removeTiene_cuentas
     * @see #getTiene_cuentasSize
     * @see #tiene_cuentasIterator
     */
    public final void appendTiene_cuentas(banco.Cuenta succ) {
        appendSuccessor(getTiene_cuentasRelationship(getMtDatabase()), succ);
    }
    /** Adds multiple objects to the end of the existing <code>tiene_cuentas</code> successors list.
     * @param succs an array of objects to add
     *
     * @see #getTiene_cuentas
     * @see #setTiene_cuentas
     * @see #removeTiene_cuentas
     * @see #getTiene_cuentasSize
     * @see #tiene_cuentasIterator
     */
    public final void appendTiene_cuentas(banco.Cuenta[] succs) {
        addSuccessors(getTiene_cuentasRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes objects from the <code>tiene_cuentas</code> successors list.
     * @param succs an array of objects to remove
     *
     * @see #getTiene_cuentas
     * @see #setTiene_cuentas
     * @see #getTiene_cuentasSize
     * @see #tiene_cuentasIterator
     */
    public void removeTiene_cuentas(banco.Cuenta[] succs) {
        removeSuccessors(getTiene_cuentasRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes one object from the <code>tiene_cuentas</code> successors list.
     * @param succ the object to remove
     *
     * @see #getTiene_cuentas
     * @see #setTiene_cuentas
     * @see #getTiene_cuentasSize
     * @see #tiene_cuentasIterator
     */
    public void removeTiene_cuentas(banco.Cuenta succ) {
        removeSuccessor(getTiene_cuentasRelationship(getMtDatabase()), succ);
    }

    /**
     * Removes all <code>tiene_cuentas</code> successors.  When the minimum cardinality
     * is 1, a new successor must be set before commit.
     */
    public final void clearTiene_cuentas() {
        clearSuccessors(getTiene_cuentasRelationship(getMtDatabase()));
    }


    /*
     * Index access methods
     */

    /* Index 'Cliente_pk' */

    /** Index <code>Cliente_pk</code> cache ID */
    private static int cliente_pkIndexCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtIndex.Loader("banco.Cliente_pk"));

    /**
     * Gets the <code>Cliente_pk</code> index descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return an index descriptor object
     */
    public static com.matisse.reflect.MtIndex getCliente_pkIndex(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtIndex)db.getCachedObject(cliente_pkIndexCID);
    }

    /**
     * Finds one <code>Cliente</code> object in index <code>Cliente_pk</code>.
     * @param db a database
     * @param dni search parameter
     * @return the matching <code>Cliente</code> object or <code>null</code> if none was found
     */
    public static Cliente lookupCliente_pk(com.matisse.MtDatabase db, String dni) {
        return (Cliente)getCliente_pkIndex(db).lookup(new Object[] {dni}, getClass(db));
    }

    /**
     * Finds <code>Cliente</code> objects in index <code>Cliente_pk</code>.
     * @param db a database
     * @param dni search parameter
     * @return the matching <code>Cliente</code> objects or an empty array if none was found
     */
    public static Cliente[] lookupObjectsCliente_pk(com.matisse.MtDatabase db, String dni) {
        return (Cliente[])getCliente_pkIndex(db).lookupObjects(new Object[] {dni}, getClass(db), Cliente.class);
    }

    /**
     * Opens an iterator on index <code>Cliente_pk</code> for class <code>Cliente</code>.
     * Each indexed attribute has a pair of "from" and "to" parameters which
     * define the search range for that attribute.  With strings, you may use
     * <code>null</code> to start "from" at the beginning or extend "to" to the end.
     * @param <E> a MtObject class     * @param db a database
     * @param fromDni search parameter
     * @param toDni search parameter
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> cliente_pkIterator(com.matisse.MtDatabase db, String fromDni, String toDni) {
        return getCliente_pkIndex(db).<E>iterator(new Object[] {fromDni}, new Object[] {toDni}, getClass(db), com.matisse.reflect.MtIndex.DIRECT, com.matisse.MtDatabase.MAX_PREFETCHING, Cliente.class);
    }

    /**
     * Opens an iterator on index <code>Cliente_pk</code> for class <code>Cliente</code>. 
     * Each indexed attribute has a pair of "from" and "to" parameters which
     * define the search range for that attribute.  With strings, you may use
     * <code>null</code> to start "from" at the beginning or extend "to" to the end.
     * @param <E> a MtObject class     * @param db a database
     * @param fromDni search parameter
     * @param toDni search parameter
     * @param filterClass a subclass; use <code>null</code> not to restrict iterator to a subclass
     * @param direction MtIndex.DIRECT or MtIndex.REVERSE
     * @param numObjPerBuffer maximum number of objects to be retrieved in each request to server
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> cliente_pkIterator(com.matisse.MtDatabase db, String fromDni, String toDni, com.matisse.reflect.MtClass filterClass, int direction, int numObjPerBuffer) {
        return getCliente_pkIndex(db).iterator(new Object[] {fromDni}, new Object[] {toDni}, filterClass, direction, numObjPerBuffer, Cliente.class);
    }

    // END of Matisse SDL Generated Code

    /*
     * You may add your own code here...
     */

    /**
     * Default constructor provided as an example.
     * You may delete this constructor or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @param db a database
     */
    public Cliente(com.matisse.MtDatabase db) {
        super(getClass(db));
    }

    /**
     * Example of <code>toString</code> method.
     * You may delete this method or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @return a string
     */
    public java.lang.String toString() {
        return super.toString() + "[Cliente]";
    }
}
