package es.marco.prado;
// Generated 3 mar. 2021 10:05:04 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private String dni;
	private String nomCliente;
	private Set cuentases = new HashSet(0);
	private Set prestamoses = new HashSet(0);

	public Clientes() {
	}

	public Clientes(String dni, String nomCliente) {
		this.dni = dni;
		this.nomCliente = nomCliente;
	}

	public Clientes(String dni, String nomCliente, Set cuentases, Set prestamoses) {
		this.dni = dni;
		this.nomCliente = nomCliente;
		this.cuentases = cuentases;
		this.prestamoses = prestamoses;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNomCliente() {
		return this.nomCliente;
	}

	public void setNomCliente(String nomCliente) {
		this.nomCliente = nomCliente;
	}

	public Set getCuentases() {
		return this.cuentases;
	}

	public void setCuentases(Set cuentases) {
		this.cuentases = cuentases;
	}

	public Set getPrestamoses() {
		return this.prestamoses;
	}

	public void setPrestamoses(Set prestamoses) {
		this.prestamoses = prestamoses;
	}

}
