package clases.marcoprado.com;
// Generated 18 ene. 2021 11:23:32 by Hibernate Tools 5.2.12.Final

/**
 * Accesos generated by hbm2java
 */
public class Accesos implements java.io.Serializable {

	private int codAcceso;
	private Estaciones estaciones;
	private String descripcion;

	public Accesos() {
	}

	public Accesos(int codAcceso, Estaciones estaciones) {
		this.codAcceso = codAcceso;
		this.estaciones = estaciones;
	}

	public Accesos(int codAcceso, Estaciones estaciones, String descripcion) {
		this.codAcceso = codAcceso;
		this.estaciones = estaciones;
		this.descripcion = descripcion;
	}

	public int getCodAcceso() {
		return this.codAcceso;
	}

	public void setCodAcceso(int codAcceso) {
		this.codAcceso = codAcceso;
	}

	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
