package clases.marcoprado.com;
// Generated 18 ene. 2021 11:23:32 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cocheras generated by hbm2java
 */
public class Cocheras implements java.io.Serializable {

	private int codCochera;
	private String nombre;
	private String direccion;
	private Set treneses = new HashSet(0);

	public Cocheras() {
	}

	public Cocheras(int codCochera) {
		this.codCochera = codCochera;
	}

	public Cocheras(int codCochera, String nombre, String direccion, Set treneses) {
		this.codCochera = codCochera;
		this.nombre = nombre;
		this.direccion = direccion;
		this.treneses = treneses;
	}

	public int getCodCochera() {
		return this.codCochera;
	}

	public void setCodCochera(int codCochera) {
		this.codCochera = codCochera;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Set getTreneses() {
		return this.treneses;
	}

	public void setTreneses(Set treneses) {
		this.treneses = treneses;
	}

}
