package clases.marcoprado.com;
// Generated 18 ene. 2021 11:23:32 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Estaciones generated by hbm2java
 */
public class Estaciones implements java.io.Serializable {

	private int codEstacion;
	private String nombre;
	private String direccion;
	private int numAccesos;
	private int numLineas;
	private int numViajesdestino;
	private int numViajesprocedencia;
	private Set lineaEstacions = new HashSet(0);
	private Set accesoses = new HashSet(0);
	private Set viajesesForEstacionDestino = new HashSet(0);
	private Set viajesesForEstacionOrigen = new HashSet(0);

	public Estaciones() {
	}

	public Estaciones(int codEstacion, int numAccesos, int numLineas, int numViajesdestino, int numViajesprocedencia) {
		this.codEstacion = codEstacion;
		this.numAccesos = numAccesos;
		this.numLineas = numLineas;
		this.numViajesdestino = numViajesdestino;
		this.numViajesprocedencia = numViajesprocedencia;
	}

	public Estaciones(int codEstacion, String nombre, String direccion, int numAccesos, int numLineas,
			int numViajesdestino, int numViajesprocedencia, Set lineaEstacions, Set accesoses,
			Set viajesesForEstacionDestino, Set viajesesForEstacionOrigen) {
		this.codEstacion = codEstacion;
		this.nombre = nombre;
		this.direccion = direccion;
		this.numAccesos = numAccesos;
		this.numLineas = numLineas;
		this.numViajesdestino = numViajesdestino;
		this.numViajesprocedencia = numViajesprocedencia;
		this.lineaEstacions = lineaEstacions;
		this.accesoses = accesoses;
		this.viajesesForEstacionDestino = viajesesForEstacionDestino;
		this.viajesesForEstacionOrigen = viajesesForEstacionOrigen;
	}

	public int getCodEstacion() {
		return this.codEstacion;
	}

	public void setCodEstacion(int codEstacion) {
		this.codEstacion = codEstacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public int getNumAccesos() {
		return this.numAccesos;
	}

	public void setNumAccesos(int numAccesos) {
		this.numAccesos = numAccesos;
	}

	public int getNumLineas() {
		return this.numLineas;
	}

	public void setNumLineas(int numLineas) {
		this.numLineas = numLineas;
	}

	public int getNumViajesdestino() {
		return this.numViajesdestino;
	}

	public void setNumViajesdestino(int numViajesdestino) {
		this.numViajesdestino = numViajesdestino;
	}

	public int getNumViajesprocedencia() {
		return this.numViajesprocedencia;
	}

	public void setNumViajesprocedencia(int numViajesprocedencia) {
		this.numViajesprocedencia = numViajesprocedencia;
	}

	public Set getLineaEstacions() {
		return this.lineaEstacions;
	}

	public void setLineaEstacions(Set lineaEstacions) {
		this.lineaEstacions = lineaEstacions;
	}

	public Set getAccesoses() {
		return this.accesoses;
	}

	public void setAccesoses(Set accesoses) {
		this.accesoses = accesoses;
	}

	public Set getViajesesForEstacionDestino() {
		return this.viajesesForEstacionDestino;
	}

	public void setViajesesForEstacionDestino(Set viajesesForEstacionDestino) {
		this.viajesesForEstacionDestino = viajesesForEstacionDestino;
	}

	public Set getViajesesForEstacionOrigen() {
		return this.viajesesForEstacionOrigen;
	}

	public void setViajesesForEstacionOrigen(Set viajesesForEstacionOrigen) {
		this.viajesesForEstacionOrigen = viajesesForEstacionOrigen;
	}

}
