package clases.marcoprado.com;
// Generated 18 ene. 2021 11:23:32 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Lineas generated by hbm2java
 */
public class Lineas implements java.io.Serializable {

	private int codLinea;
	private String nombre;
	private Set lineaEstacions = new HashSet(0);
	private Set treneses = new HashSet(0);

	public Lineas() {
	}

	public Lineas(int codLinea) {
		this.codLinea = codLinea;
	}

	public Lineas(int codLinea, String nombre, Set lineaEstacions, Set treneses) {
		this.codLinea = codLinea;
		this.nombre = nombre;
		this.lineaEstacions = lineaEstacions;
		this.treneses = treneses;
	}

	public int getCodLinea() {
		return this.codLinea;
	}

	public void setCodLinea(int codLinea) {
		this.codLinea = codLinea;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getLineaEstacions() {
		return this.lineaEstacions;
	}

	public void setLineaEstacions(Set lineaEstacions) {
		this.lineaEstacions = lineaEstacions;
	}

	public Set getTreneses() {
		return this.treneses;
	}

	public void setTreneses(Set treneses) {
		this.treneses = treneses;
	}

}
