package clases.marcoprado.com;
// Generated 18 ene. 2021 11:23:32 by Hibernate Tools 5.2.12.Final

/**
 * Trenes generated by hbm2java
 */
public class Trenes implements java.io.Serializable {

	private int codTren;
	private Cocheras cocheras;
	private Lineas lineas;
	private String nombre;
	private String tipo;

	public Trenes() {
	}

	public Trenes(int codTren, Cocheras cocheras, Lineas lineas) {
		this.codTren = codTren;
		this.cocheras = cocheras;
		this.lineas = lineas;
	}

	public Trenes(int codTren, Cocheras cocheras, Lineas lineas, String nombre, String tipo) {
		this.codTren = codTren;
		this.cocheras = cocheras;
		this.lineas = lineas;
		this.nombre = nombre;
		this.tipo = tipo;
	}

	public int getCodTren() {
		return this.codTren;
	}

	public void setCodTren(int codTren) {
		this.codTren = codTren;
	}

	public Cocheras getCocheras() {
		return this.cocheras;
	}

	public void setCocheras(Cocheras cocheras) {
		this.cocheras = cocheras;
	}

	public Lineas getLineas() {
		return this.lineas;
	}

	public void setLineas(Lineas lineas) {
		this.lineas = lineas;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
