package clases.marcoprado.com;
// Generated 18 ene. 2021 11:23:32 by Hibernate Tools 5.2.12.Final

/**
 * Viajes generated by hbm2java
 */
public class Viajes implements java.io.Serializable {

	private int codViaje;
	private Estaciones estacionesByEstacionDestino;
	private Estaciones estacionesByEstacionOrigen;
	private String nombre;

	public Viajes() {
	}

	public Viajes(int codViaje, Estaciones estacionesByEstacionDestino, Estaciones estacionesByEstacionOrigen) {
		this.codViaje = codViaje;
		this.estacionesByEstacionDestino = estacionesByEstacionDestino;
		this.estacionesByEstacionOrigen = estacionesByEstacionOrigen;
	}

	public Viajes(int codViaje, Estaciones estacionesByEstacionDestino, Estaciones estacionesByEstacionOrigen,
			String nombre) {
		this.codViaje = codViaje;
		this.estacionesByEstacionDestino = estacionesByEstacionDestino;
		this.estacionesByEstacionOrigen = estacionesByEstacionOrigen;
		this.nombre = nombre;
	}

	public int getCodViaje() {
		return this.codViaje;
	}

	public void setCodViaje(int codViaje) {
		this.codViaje = codViaje;
	}

	public Estaciones getEstacionesByEstacionDestino() {
		return this.estacionesByEstacionDestino;
	}

	public void setEstacionesByEstacionDestino(Estaciones estacionesByEstacionDestino) {
		this.estacionesByEstacionDestino = estacionesByEstacionDestino;
	}

	public Estaciones getEstacionesByEstacionOrigen() {
		return this.estacionesByEstacionOrigen;
	}

	public void setEstacionesByEstacionOrigen(Estaciones estacionesByEstacionOrigen) {
		this.estacionesByEstacionOrigen = estacionesByEstacionOrigen;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
