package es.clases.marco;
// Generated 3 mar. 2021 12:16:30 by Hibernate Tools 5.2.12.Final

/**
 * Prestamos generated by hbm2java
 */
public class Prestamos implements java.io.Serializable {

	private int idPrestamo;
	private Clientes clientes;
	private int plazo;
	private int cantidad;

	public Prestamos() {
	}

	public Prestamos(int idPrestamo, Clientes clientes, int plazo, int cantidad) {
		this.idPrestamo = idPrestamo;
		this.clientes = clientes;
		this.plazo = plazo;
		this.cantidad = cantidad;
	}

	public int getIdPrestamo() {
		return this.idPrestamo;
	}

	public void setIdPrestamo(int idPrestamo) {
		this.idPrestamo = idPrestamo;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public int getPlazo() {
		return this.plazo;
	}

	public void setPlazo(int plazo) {
		this.plazo = plazo;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

}
