/*
 * Clientes.java

 *
 * Generated with Matisse Schema Definition Language 9.1.12
 * Generation date: Sun Jan 31 12:53:16 2021
 */

// Note: the package and extends declarations are generated by mt_sdl, do not modify them

package clientesPedidos;

import com.matisse.reflect.*;

/**
 * <code>Clientes</code> is a schema class generated by <code>mt_sdl</code>.
 * Any user-written classes will be found at the end of the file, after
 * the '// END of Matisse SDL Generated Code' comment.
 * Attribute types, default values, and relationship minimum and maximum
 * cardinality are stored in the database itself, not in this source code.
 * For more information, see <i>Getting Started with MATISSE</i>.
 */
public class Clientes extends com.matisse.reflect.MtObject {

    // BEGIN Matisse SDL Generated Code
    // DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
    /*
     * Generated with Matisse Schema Definition Language 9.1.12
     * Generation Date: Sun Jan 31 12:53:16 2021
     */

    /*
     * Class variables and methods
     */

    /** Class <code>Clientes</code> cache ID */
    private static int CID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtClass.Loader("clientesPedidos.Clientes"));

    /**
     * Gets the <code>Clientes</code> class descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a class descriptor
     */
    public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtClass)db.getCachedObject(CID);
    }

    /**
     * Factory constructor. This constructor is called by <code>MtObjectFactory</code>.
     * It is public for technical reasons but is not intended to be called
     * directly by user methods.
     * @param db a database
     * @param mtOid an existing object ID in the database
     */
    public Clientes(com.matisse.MtDatabase db, int mtOid)  {
        super(db, mtOid);
    }

    /**
     * Cascaded constructor, used by subclasses to create a new object in the database.
     * It is protected for technical reasons but is not intended to be called
     * directly by user methods.
     * @param mtCls a class descriptor (the class to instantiate)
     */
    protected Clientes(com.matisse.reflect.MtClass mtCls)  {
        super(mtCls);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>instanceIterator(Clientes.class);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>instanceIterator(numObjPerBuffer, Clientes.class);
    }

    /**
     * Counts the number of instances of this class (and its subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getInstanceNumber();
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>ownInstanceIterator(Clientes.class);
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, Clientes.class);
    }

    /**
     * Counts the number of own instances of this class (excluding subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getOwnInstanceNumber();
    }

    /*
     * Attribute access methods
     */

    /* Attribute 'dni' */

    /** Attribute <code>dni</code> cache ID */
    private static int dniCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("dni",CID));

    /**
     * Gets the <code>dni</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getDniAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(dniCID);
    }


    /**
     * Gets the <code>dni</code> attribute value.
     * @return the value
     *
     * @see #setDni
     * @see #removeDni
     */
    public final String getDni() {
        return getString(getDniAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>dni</code> attribute value.
     * @param val the new value
     *
     * @see #getDni
     * @see #removeDni
     */
    public final void setDni(String val) {
        setString(getDniAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>dni</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getDni
     * @see #setDni
     */
    public final void removeDni() {
        removeValue(getDniAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getDni
     * @see #setDni
     */
    public final boolean isDniDefaultValue() {
        return isDefaultValue(getDniAttribute(getMtDatabase()));
    }


    /* Attribute 'nombre' */

    /** Attribute <code>nombre</code> cache ID */
    private static int nombreCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("nombre",CID));

    /**
     * Gets the <code>nombre</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getNombreAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(nombreCID);
    }


    /**
     * Gets the <code>nombre</code> attribute value.
     * @return the value
     *
     * @see #setNombre
     * @see #removeNombre
     */
    public final String getNombre() {
        return getString(getNombreAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>nombre</code> attribute value.
     * @param val the new value
     *
     * @see #getNombre
     * @see #removeNombre
     */
    public final void setNombre(String val) {
        setString(getNombreAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>nombre</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getNombre
     * @see #setNombre
     */
    public final void removeNombre() {
        removeValue(getNombreAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getNombre
     * @see #setNombre
     */
    public final boolean isNombreDefaultValue() {
        return isDefaultValue(getNombreAttribute(getMtDatabase()));
    }


    /*
     * Relationship access methods
     */

    /* Relationship 'tiene_pedidos' */

    /** Relationship <code>tiene_pedidos</code> cache ID */
    private static int tiene_pedidosCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtRelationship.Loader("tiene_pedidos",CID));

    /**
     * Gets the <code>tiene_pedidos</code> relationship descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a relationship descriptor object
     */
    public static com.matisse.reflect.MtRelationship getTiene_pedidosRelationship(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtRelationship)db.getCachedObject(tiene_pedidosCID);
    }

    /**
     * Gets the <code>tiene_pedidos</code> relationship's successors.
     * @return an array of objects
     *
     * @see #getTiene_pedidosSize
     * @see #tiene_pedidosIterator
     * @see #setTiene_pedidos
     * @see #removeTiene_pedidos
     */
    public final clientesPedidos.Pedidos[] getTiene_pedidos() {
        return (clientesPedidos.Pedidos[])getSuccessors(getTiene_pedidosRelationship(getMtDatabase()), clientesPedidos.Pedidos.class);
    }

    /**
     * Counts the <code>tiene_pedidos</code> relationship's successors.
     * @return the number of successors
     *
     * @see #getTiene_pedidos
     * @see #tiene_pedidosIterator
     * @see #setTiene_pedidos
     * @see #removeTiene_pedidos
     */
    public final int getTiene_pedidosSize() {
        return getSuccessorSize(getTiene_pedidosRelationship(getMtDatabase()));
    }

    /**
     * Opens an iterator on the <code>tiene_pedidos</code> relationship's successors.
     * @param <E> a MtObject class     * @return an object iterator
     *
     * @see #getTiene_pedidos
     * @see #getTiene_pedidosSize
     * @see #setTiene_pedidos
     * @see #removeTiene_pedidos
     */
    public final <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> tiene_pedidosIterator() {
        return this.<E>successorIterator(getTiene_pedidosRelationship(getMtDatabase()), clientesPedidos.Pedidos.class);
    }

    /**
     * Sets the <code>tiene_pedidos</code> relationship's successors.
     * @param succs an array of objects
     *
     * @see #getTiene_pedidos
     * @see #getTiene_pedidosSize
     * @see #tiene_pedidosIterator
     * @see #removeTiene_pedidos
     */
    public final void setTiene_pedidos(clientesPedidos.Pedidos[] succs) {
        setSuccessors(getTiene_pedidosRelationship(getMtDatabase()), succs);
    }

    /**
     * Inserts one object at the beginning of the existing <code>tiene_pedidos</code> successors list.
     * @param succ the object to add
     *
     * @see #getTiene_pedidos
     * @see #getTiene_pedidosSize
     * @see #tiene_pedidosIterator
     * @see #setTiene_pedidos
     * @see #removeTiene_pedidos
     */
    public final void prependTiene_pedidos(clientesPedidos.Pedidos succ) {
        prependSuccessor(getTiene_pedidosRelationship(getMtDatabase()), succ);
    }

    /**
     * Adds one object to the end of the existing <code>tiene_pedidos</code> successors list.
     * @param succ the object to add
     *
     * @see #getTiene_pedidos
     * @see #setTiene_pedidos
     * @see #removeTiene_pedidos
     * @see #getTiene_pedidosSize
     * @see #tiene_pedidosIterator
     */
    public final void appendTiene_pedidos(clientesPedidos.Pedidos succ) {
        appendSuccessor(getTiene_pedidosRelationship(getMtDatabase()), succ);
    }
    /** Adds multiple objects to the end of the existing <code>tiene_pedidos</code> successors list.
     * @param succs an array of objects to add
     *
     * @see #getTiene_pedidos
     * @see #setTiene_pedidos
     * @see #removeTiene_pedidos
     * @see #getTiene_pedidosSize
     * @see #tiene_pedidosIterator
     */
    public final void appendTiene_pedidos(clientesPedidos.Pedidos[] succs) {
        addSuccessors(getTiene_pedidosRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes objects from the <code>tiene_pedidos</code> successors list.
     * @param succs an array of objects to remove
     *
     * @see #getTiene_pedidos
     * @see #setTiene_pedidos
     * @see #getTiene_pedidosSize
     * @see #tiene_pedidosIterator
     */
    public void removeTiene_pedidos(clientesPedidos.Pedidos[] succs) {
        removeSuccessors(getTiene_pedidosRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes one object from the <code>tiene_pedidos</code> successors list.
     * @param succ the object to remove
     *
     * @see #getTiene_pedidos
     * @see #setTiene_pedidos
     * @see #getTiene_pedidosSize
     * @see #tiene_pedidosIterator
     */
    public void removeTiene_pedidos(clientesPedidos.Pedidos succ) {
        removeSuccessor(getTiene_pedidosRelationship(getMtDatabase()), succ);
    }

    /**
     * Removes all <code>tiene_pedidos</code> successors.  When the minimum cardinality
     * is 1, a new successor must be set before commit.
     */
    public final void clearTiene_pedidos() {
        clearSuccessors(getTiene_pedidosRelationship(getMtDatabase()));
    }


    // END of Matisse SDL Generated Code

    /*
     * You may add your own code here...
     */

    /**
     * Default constructor provided as an example.
     * You may delete this constructor or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @param db a database
     */
    public Clientes(com.matisse.MtDatabase db) {
        super(getClass(db));
    }

    /**
     * Example of <code>toString</code> method.
     * You may delete this method or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @return a string
     */
    public java.lang.String toString() {
        return super.toString() + "[Clientes]";
    }
}
