package clases.marco.com;
// Generated 13 ene. 2021 20:24:25 by Hibernate Tools 5.2.12.Final

/**
 * ProyectoSedeId generated by hbm2java
 */
public class ProyectoSedeId implements java.io.Serializable {

	private int idProy;
	private int idSede;

	public ProyectoSedeId() {
	}

	public ProyectoSedeId(int idProy, int idSede) {
		this.idProy = idProy;
		this.idSede = idSede;
	}

	public int getIdProy() {
		return this.idProy;
	}

	public void setIdProy(int idProy) {
		this.idProy = idProy;
	}

	public int getIdSede() {
		return this.idSede;
	}

	public void setIdSede(int idSede) {
		this.idSede = idSede;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProyectoSedeId))
			return false;
		ProyectoSedeId castOther = (ProyectoSedeId) other;

		return (this.getIdProy() == castOther.getIdProy()) && (this.getIdSede() == castOther.getIdSede());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProy();
		result = 37 * result + this.getIdSede();
		return result;
	}

}
