package es.marco.hibernate;
// Generated 2 mar. 2021 23:17:35 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa implements java.io.Serializable {

	private String codEmpresa;
	private String nombre;
	private Set reservas = new HashSet(0);

	public Empresa() {
	}

	public Empresa(String codEmpresa, String nombre) {
		this.codEmpresa = codEmpresa;
		this.nombre = nombre;
	}

	public Empresa(String codEmpresa, String nombre, Set reservas) {
		this.codEmpresa = codEmpresa;
		this.nombre = nombre;
		this.reservas = reservas;
	}

	public String getCodEmpresa() {
		return this.codEmpresa;
	}

	public void setCodEmpresa(String codEmpresa) {
		this.codEmpresa = codEmpresa;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getReservas() {
		return this.reservas;
	}

	public void setReservas(Set reservas) {
		this.reservas = reservas;
	}

}
