package es.marco.hibernate;
// Generated 2 mar. 2021 23:17:35 by Hibernate Tools 5.2.12.Final

/**
 * ReservaId generated by hbm2java
 */
public class ReservaId implements java.io.Serializable {

	private String codSala;
	private int diaMes;

	public ReservaId() {
	}

	public ReservaId(String codSala, int diaMes) {
		this.codSala = codSala;
		this.diaMes = diaMes;
	}

	public String getCodSala() {
		return this.codSala;
	}

	public void setCodSala(String codSala) {
		this.codSala = codSala;
	}

	public int getDiaMes() {
		return this.diaMes;
	}

	public void setDiaMes(int diaMes) {
		this.diaMes = diaMes;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReservaId))
			return false;
		ReservaId castOther = (ReservaId) other;

		return ((this.getCodSala() == castOther.getCodSala()) || (this.getCodSala() != null
				&& castOther.getCodSala() != null && this.getCodSala().equals(castOther.getCodSala())))
				&& (this.getDiaMes() == castOther.getDiaMes());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodSala() == null ? 0 : this.getCodSala().hashCode());
		result = 37 * result + this.getDiaMes();
		return result;
	}

}
