package es.marco.hibernate;
// Generated 2 mar. 2021 23:17:35 by Hibernate Tools 5.2.12.Final

/**
 * Reserva generated by hbm2java
 */
public class Reserva implements java.io.Serializable {

	private ReservaId id;
	private Empresa empresa;
	private Sala sala;
	private String nomActividad;

	public Reserva() {
	}

	public Reserva(ReservaId id, Empresa empresa, Sala sala) {
		this.id = id;
		this.empresa = empresa;
		this.sala = sala;
	}

	public Reserva(ReservaId id, Empresa empresa, Sala sala, String nomActividad) {
		this.id = id;
		this.empresa = empresa;
		this.sala = sala;
		this.nomActividad = nomActividad;
	}

	public ReservaId getId() {
		return this.id;
	}

	public void setId(ReservaId id) {
		this.id = id;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public Sala getSala() {
		return this.sala;
	}

	public void setSala(Sala sala) {
		this.sala = sala;
	}

	public String getNomActividad() {
		return this.nomActividad;
	}

	public void setNomActividad(String nomActividad) {
		this.nomActividad = nomActividad;
	}

}
