package es.marco.hibernate;
// Generated 2 mar. 2021 23:17:35 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Sala generated by hbm2java
 */
public class Sala implements java.io.Serializable {

	private String codSala;
	private String descripcion;
	private Double precio;
	private Set reservas = new HashSet(0);

	public Sala() {
	}

	public Sala(String codSala) {
		this.codSala = codSala;
	}

	public Sala(String codSala, String descripcion, Double precio, Set reservas) {
		this.codSala = codSala;
		this.descripcion = descripcion;
		this.precio = precio;
		this.reservas = reservas;
	}

	public String getCodSala() {
		return this.codSala;
	}

	public void setCodSala(String codSala) {
		this.codSala = codSala;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}

	public Set getReservas() {
		return this.reservas;
	}

	public void setReservas(Set reservas) {
		this.reservas = reservas;
	}

}
